alter user AZ_MANAGER default TABLESPACE users QUOTA UNLIMITED on users;

INSERT INTO AZ_MANAGER.MEMBER (ID,PW,ADDRESS) VALUES ('abc','aaa',NULL);

SELECT COUNT(*) FROM AZ_MANAGER.MEMBER WHERE ID = 'abc';
SELECT * FROM AZ_MANAGER.MEMBER WHERE ID = abc;